Tochemey/goakt

actors/api.go
actors/behavior.go
actors/context.go
actors/errors.go
actors/helper_test.go
actors/pid.go
actors/receive_loop.go
readme.md

feat: implement behavior stack

---

contributing.md

Signed-off-by: Arsene <tochemey@hotmail.com>

feat: add contribution guide

---

readme.md

docs: add go reference badge

---

actors/actor_system.go
actors/constants.go
actors/option.go
actors/option_test.go
actors/pid.go
actors/pid_option.go
actors/pid_option_test.go
go.mod

This will help enhance spawn actors

refactor: add init timeout for actor

---

actors/actor_system.go
actors/actor_system_test.go
cluster/cluster.go
cluster/cluster_test.go

fix: remove actor from cluster when passivation is enabled

---

actors/actor_system.go
actors/pid.go

fix: set init timeout on actor system and properly reset it

---

actors/context.go
actors/context_test.go
actors/pid.go
actors/pid_test.go
examples/actor-receive/main.go

feat: add batch tell and batch ask

---

actors/context.go
actors/context_test.go
actors/pid.go

feat: add remote batch messaging to receiveContext

---

discovery/nats/discovery.go
discovery/nats/discovery_test.go

fix: fix NATs discovery provider bug

---

actors/context_test.go
actors/pid.go
examples/actor-cluster/dnssd/actors/actors.go
examples/actor-cluster/k8s/actors/actors.go
examples/actor-observability/main.go
examples/actor-to-actor/main.go
examples/remoting/ping/main.go
examples/remoting/pong/main.go

refactor: skip system messages from ctx.Unhandled method

---

actors/path.go
actors/pid.go
actors/pid_test.go

feat: add ID and Equals methods to PID

---

actors/actor_system.go
actors/actor_system_test.go

fix: create a new copy of mailbox each time an actor is created

---

actors/pid.go
actors/pid_test.go

fix: fix deadlock issue when creating child actor

---

actors/actor_system.go

fix: use underlying message processor than the PID

---

actors/api.go
actors/pid.go
actors/pid_test.go
actors/receive_context.go

perf: add sync loop to message processing

---

README.md
testkit/option.go
testkit/probe.go
testkit/probe_test.go
testkit/testkit.go

refactor: refactor ExpectMessage and ExpectMessageWithin

---

README.md
actors/actor_system_test.go
actors/helper_test.go
actors/pid_test.go
actors/redistribution_test.go
client/client_test.go
discovery/nats/config.go
discovery/nats/config_test.go
discovery/nats/discovery.go
discovery/nats/discovery_test.go
internal/cluster/engine_test.go

BREAKING CHANGE: - Remove host node param

refactor: refactor nats discovery

---

actors/actor_system.go

fix(bugs): retain dns name and resolves ip addresses

---

actors/actor_system.go
actors/actor_system_test.go
actors/errors.go
actors/janitor.go
actors/mock_test.go
actors/pid.go
actors/rebalancer.go
actors/rebalancer_test.go
internal/cluster/engine.go

fix(bugs): enforce actors uniqueness creation in cluster

---

bench/actor.go
bench/actor_test.go
internal/cluster/engine.go
internal/cluster/option.go
internal/cluster/option_test.go

feat: enhance cluster storage key/value size

---

actor/actor_system.go
actor/actor_system_test.go
actor/mock_test.go
actor/option.go
actor/option_test.go
actor/rebalancer_test.go

feat: :sparkles: add relocation disabled option to actor system

---

actor/actor_system.go
actor/actor_system_test.go
actor/mock_test.go
client/client_test.go
extension/extension.go

feat: add extension ID validation

---

actor/death_watch.go
testkit/probe.go
testkit/probe_test.go
testkit/testkit.go

feat: :sparkles: enhance testkit

---

memory/memory_windows.go

fix: windows compilation error

---

.github/workflows/build.yml
actor/actor_ref.go
actor/actor_ref_test.go
actor/actor_system.go
actor/mock_test.go
actor/pid.go
actor/pid_test.go
actor/rebalancer.go
actor/supervisor.go
goaktpb/goakt.pb.go
internal/cluster/codec.go
internal/cluster/codec_test.go
internal/cluster/engine.go
internal/cluster/engine_test.go
internal/internalpb/actor.pb.go
internal/internalpb/peers.pb.go
internal/internalpb/supervision.pb.go
mocks/cluster/interface.go
protos/goakt/goakt.proto
protos/internal/actor.proto
protos/internal/peers.proto
protos/internal/supervision.proto

feat: add escalate supervisor directive

---

.github/workflows/pr.yml
README.md
actor/actor_system.go
actor/mock_test.go
actor/pid.go
actor/pid_test.go
actor/receive_context.go
actor/receive_context_test.go
actor/remoting.go
actor/remoting_test.go
address/address.go
address/address_test.go
go.mod
go.sum
goaktpb/goakt.pb.go
internal/internalpb/internalpbconnect/remoting.connect.go
internal/internalpb/remoting.pb.go
protos/goakt/goakt.proto
protos/internal/remoting.proto

feat: :sparkles: add Reinstate mechanism

---

actor/actor_system.go
actor/actor_system_test.go
actor/remoting.go
actor/remoting_test.go
address/address.go
client/actor.go
client/balancer.go
client/client.go
client/client_test.go

refactor: enhance cluster client and bugs fixing

---

README.md

This PR makes the getting started documentation a little bit more clear. Especially for those who are not completely familar with golang, semantic commits or earthly.

docs: add contributing instructions

---

actor/mock_test.go
actor/pid.go
actor/pid_test.go

fix: push post start message during restart

---

actor/rebalancer_test.go
go.mod
internal/cluster/engine.go

fix: fix actor shutdown cleanup bug in cluster

---

actor/actor_system.go
actor/actor_system_test.go
actor/death_watch.go
actor/death_watch_test.go
internal/cluster/binary_queue.go
internal/cluster/engine.go
internal/cluster/go_scheduler.go

- Refactor cluster engine to use MPSC queue that performs better under load than channels. This will prepare the way to accommodate Grains as well
- Properly sequence actor system startup

refactor: refactor cluster engine and actor system startup

---

actor/actor_system.go

Replaced sync.Mutex with sync.RWMutex in the actor system to allow multiple readers to access state concurrently. This improves performance in scenarios where reads are frequent and writes are infrequent, ensuring better synchronization without sacrificing throughput.
closes #817

refactor: replace Mutex with RWMutex for improved concurrency

---

actor/actor_system.go

fix: fix unlock of unlocked RWMutex

---

actor/actor_system.go

refactor: refactor peer state loop to avoid context cancellation

---

actor/actor_system.go

refactor(k8s): resync state during cluster events

---

actor/actor_system.go
actor/actor_system_test.go
actor/pid.go

refactor: :necktie: hardened ActorOf and ActorExists methods to cater for timing issue during shutdown

---

internal/brotli/brotli.go
internal/brotli/brotli_test.go
internal/brotli/pool.go

fix: fix brotli implementation

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/stale.yml
.golangci.yml
actor/receive_context.go
actor/receive_context_test.go
actor/unbounded_fair_mailbox.go
actor/unbounded_fair_mailbox_test.go
actor/unbounded_segmented_mailbox.go
actor/unbounded_segmented_mailbox_test.go

feat: ✨ added new built-in mailboxes

---

actor/actor_system_test.go
actor/fixtures_test.go

test: add additional tests
